services:
  standalone-chrome:
    image: selenium/standalone-chrome
    container_name: standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 10s
      timeout: 60s
      retries: 10

  docker-python:
    build: .
    container_name: docker-python
    volumes: 
      - .:/mnt
    command: python main.py
    depends_on:
      - standalone-chrome
  